### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by bremussolutions** [geoperez/PayPalCore#2]
Is it possible to convert the solution into a Visual Studio 2017 project and pubish? I'm not able to convert the solution.

**Comment by geoperez** [comment]
Let me give it a try.

**Comment by Sun3** [comment]
Same here, getting error and project not loading.

Thanks.

**Comment by bremussolutions** [comment]
A quick workaround: Copy all files into a new Visual Studio 2017 class library. Compile. Have fun!

@geoperez Do want the project as a zip?

**Comment by geoperez** [comment]
Can you create a pull request?

**Comment by geoperez** [comment]
All done with NET Standard 1.6 as target.
